name: Cypress Cucumber Test

on:
  push:
    branches: [main]

jobs:
  cypress_run:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.15.1]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4

      with:
        node-version: ${{ matrix.node-version }}

    - name: Update node manager
      run: npm i npm@latest

    - name: Install all dependencies\
      run: npm i

    - name: Insatll Cypress
      run: npm install cypress

    - name: Install badeball/cypress-cucumber-preprocessor
      run: npm install @badeball/cypress-cucumber-preprocessor

    - name: Install @bahmutov/cypress-esbuild-preprocessor
      run: npm install @bahmutov/cypress-esbuild-preprocessor

    - name: install multiple cucumber reporter dev
      run: npm install multiple-cucumber-html-reporter --save-dev

    - name: run test
      run: npm run test:run

    - name: Generate report
      if: always()
      run: npm run cypress:report

    - name: Upload artifact cucumber-report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cucumber-report
      path: ./reports/cucumber-htmlreport

    - name: Deploy to Page
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: reports/cucumber-htmlreport/
